repos:
  - repo: https://github.com/asottile/reorder_python_imports.git
    rev: v3.8.3
    hooks:
      - id: reorder-python-imports
        name: Reorder Python imports
        types: [file, python]
        exclude: ^test/
  - repo: https://gitlab.inspir.work/mirrors/mirrors_psf/black.git
    rev: 22.8.0
    hooks:
      - id: black
        additional_dependencies: ['click==8.0.4']
        args: [--line-length=120]
        types: [file, python]
  - repo: https://gitlab.inspir.work/mirrors/mirros_pycqa/flake8.git
    rev: 5.0.4
    hooks:
      - id: flake8
        args: [--max-line-length=120, --max-complexity=18, --select=B,C,E,F,W,T4,B9 --ignore=E203,E266,E501,E503,W503,F403,E231,B950,C901,B008]
        types: [file, python]
        additional_dependencies: [flake8-bugbear]
        exclude: ^test/
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v4.3.0
    hooks:
      - id: check-byte-order-marker
        types: [file, python]
      - id: trailing-whitespace
        types: [file, python]
      - id: end-of-file-fixer
        types: [file, python]
